### ISSUE TITLE
Assignment 5-4

### ISSUE THREAD

**Issue by ambethia** [cateia97/assignments#26]
# Week 5 - Day 4
## Part I

Fork the `todos-cli` repo we worked on this afternoon and complete it's implementation accordning to the `README`:

  https://github.com/tiy-tpa-rails-q2-2015/todos-cli
## Part II

Create a Rails app that has the same features as your CLI todo app.
- [ ] Include all the functionality from your CLI todo app's README.
- [ ] Deploy to heroku, put some lists up on heroku for me to look at.
- [ ] Use Foundation or Bootstrap to make it look nice.
- [ ] No scaffolding!
- [ ] Link me both your app's repository and deployed Heroku app before you close out the issue.

*\* Bonus *\* 
- [ ] Add User authentication (hand rolled, or checkout `devise`), make lists belong to the user who's logged in. That use should only see their own lists.

**Comment by bristolkr** [comment]
CLI: https://github.com/cateia97/todos-cli
